/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleTest2;

public class App {
    public String getGreeting() {
        return "Hello world first.";
    }

    public String getGreetingNumberTwo() {
        return "Hello world number two.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreetingNumberTwo());
    }
}
