/*
 * This Java source file was generated by the Gradle 'init' task.
 * More updates will be added tomorrow.
 */
package gradleTest2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppHasCorrectGreetingText() {
        App classUnderTest = new App();
        assertEquals("Hello world first.", classUnderTest.getGreeting());
    }

}
